### PR TITLE
A couple small but crucial improvements

### PR DESCRIPTION
**Pull request by ThatsJustCheesy**
Among some trivial localization fixes, also addresses Xcode crashing upon load of basically any generated NIB file. See description of “Add NSNextOid…” for details.

Also, @yozik04, I used your brief modernization commit. I hope you don't mind. :)

I realize there is no formal license on this project, but nonetheless I hereby dedicate the contents of these commits to the public domain (if that is okay with the original author, of course).

### CODE REVIEW

**Comment by yozik04** [comment]
:) of course I do not mind. I already forgot what I did there.

**Comment by penx** [comment]
@ThatsJustCheesy  when using your branch with Xcode 11 and Catalina, Xcode crashes if I select 'Open and Upgrade' when trying to open the nib,

I've also tried `ibtool decompiled.nib --upgrade --write new.xib` as suggested by @latenitefilms in #5 but that doesn't seem to output a file and also doesn't log any errors.

Any ideas?

**Comment by ThatsJustCheesy** [comment]
Sorry, I'm not sure how to fix it. It's honestly a miracle that this solution has kept working for this long, since it entails

1. Tricking Xcode into opening a compiled nib document (whose format is an opaque NSKeyedArchiver archive) by making it look like a document in a long-bygone super-legacy editable `nib` format
2. Xcode's legacy document converter having to convert a "legacy" document that somehow manages to incorporate _modern_ features (autolayout, CoreAnimation, etc.) 

So it's not surprising that it breaks. I too would love to have it fixed, but I'm not sure how feasible that would be without an extensive reverse engineering effort.

But I'm all ears!

**Comment by ThatsJustCheesy** [comment]
Closing due to abandonment.

**Pull request closed without merging**
